### ISSUE TITLE
add Google Analytics tracking to HTML header

### ISSUE THREAD

**Issue by SBKraines** [SBKraines/song-of-existence#1]
Hi @akraines , do you think you can add the google analytics tracker to the header? I didn't want to mess with your code.
Love Chaya:

Tracking ID
UA-145936561-1
Status
No data received in past 48 hours. Learn more
Website Tracking
Global Site Tag (gtag.js)
This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.
````

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145936561-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-145936561-1');
</script>`
```

**Comment by akraines** [comment]
Done
